version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: billing-postgres
    environment:
      POSTGRES_DB: billing
      POSTGRES_USER: billing
      POSTGRES_PASSWORD: billing
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U billing"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: billing-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/billing?options=-c%20TimeZone=Asia/Kolkata
      SPRING_DATASOURCE_USERNAME: billing
      SPRING_DATASOURCE_PASSWORD: billing
      JWT_SECRET: utility-billing-platform-super-secret-key-minimum-256-bits-long
      JWT_EXPIRATION_MS: 86400000
      DUSER_TIMEZONE: UTC
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: billing-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

  prometheus:
    image: prom/prometheus:latest
    container_name: billing-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: billing-grafana
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus

volumes:
  pgdata: